// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0--rc1
// source: apigetway.proto

// имя пакета, в результирующем go-файле это сохраниться

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShortNew struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// номер записи
	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// заголовок публикации
	Title       string `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"` // содержание публикации
	Time        int64  `protobuf:"varint,4,opt,name=Time,proto3" json:"Time,omitempty"`              // время публикации
	Url         string `protobuf:"bytes,5,opt,name=Url,proto3" json:"Url,omitempty"`                 // ссылка на источник
	Hash        int64  `protobuf:"varint,6,opt,name=Hash,proto3" json:"Hash,omitempty"`              //Хеш  новости
}

func (x *ShortNew) Reset() {
	*x = ShortNew{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigetway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortNew) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortNew) ProtoMessage() {}

func (x *ShortNew) ProtoReflect() protoreflect.Message {
	mi := &file_apigetway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortNew.ProtoReflect.Descriptor instead.
func (*ShortNew) Descriptor() ([]byte, []int) {
	return file_apigetway_proto_rawDescGZIP(), []int{0}
}

func (x *ShortNew) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ShortNew) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShortNew) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ShortNew) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ShortNew) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShortNew) GetHash() int64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

type Forlist struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Forlist) Reset() {
	*x = Forlist{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigetway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Forlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forlist) ProtoMessage() {}

func (x *Forlist) ProtoReflect() protoreflect.Message {
	mi := &file_apigetway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forlist.ProtoReflect.Descriptor instead.
func (*Forlist) Descriptor() ([]byte, []int) {
	return file_apigetway_proto_rawDescGZIP(), []int{1}
}

type Page struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page   int32 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Offset int32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *Page) Reset() {
	*x = Page{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigetway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_apigetway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_apigetway_proto_rawDescGZIP(), []int{2}
}

func (x *Page) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Page) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigetway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_apigetway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_apigetway_proto_rawDescGZIP(), []int{3}
}

func (x *Id) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ArrayShortNews struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sl []*ShortNew `protobuf:"bytes,1,rep,name=Sl,proto3" json:"Sl,omitempty"`
}

func (x *ArrayShortNews) Reset() {
	*x = ArrayShortNews{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigetway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayShortNews) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayShortNews) ProtoMessage() {}

func (x *ArrayShortNews) ProtoReflect() protoreflect.Message {
	mi := &file_apigetway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayShortNews.ProtoReflect.Descriptor instead.
func (*ArrayShortNews) Descriptor() ([]byte, []int) {
	return file_apigetway_proto_rawDescGZIP(), []int{4}
}

func (x *ArrayShortNews) GetSl() []*ShortNew {
	if x != nil {
		return x.Sl
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   bool   `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_apigetway_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_apigetway_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_apigetway_proto_rawDescGZIP(), []int{5}
}

func (x *Result) GetRet() bool {
	if x != nil {
		return x.Ret
	}
	return false
}

func (x *Result) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_apigetway_proto protoreflect.FileDescriptor

var file_apigetway_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x70, 0x69, 0x67, 0x65, 0x74, 0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x08, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x77, 0x73, 0x22, 0x8c, 0x01, 0x0a, 0x08,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x22, 0x09, 0x0a, 0x07, 0x46, 0x6f,
	0x72, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x18, 0x0a, 0x02, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x50,
	0x61, 0x67, 0x65, 0x22, 0x34, 0x0a, 0x0e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x53, 0x68, 0x6f, 0x72,
	0x74, 0x4e, 0x65, 0x77, 0x73, 0x12, 0x22, 0x0a, 0x02, 0x53, 0x6c, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x4e, 0x65, 0x77, 0x52, 0x02, 0x53, 0x6c, 0x22, 0x30, 0x0a, 0x06, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xed, 0x01, 0x0a, 0x0b,
	0x4e, 0x65, 0x77, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x41,
	0x64, 0x64, 0x4e, 0x65, 0x77, 0x12, 0x12, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x77, 0x73,
	0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x1a, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x5f,
	0x6e, 0x65, 0x77, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x39, 0x0a,
	0x07, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x73, 0x12, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6e,
	0x65, 0x77, 0x73, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x65,
	0x77, 0x73, 0x1a, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x28, 0x01, 0x12, 0x37, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x6c,
	0x69, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x41,
	0x72, 0x72, 0x61, 0x79, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x22, 0x00, 0x30,
	0x01, 0x12, 0x38, 0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x1a, 0x18, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x6e, 0x65, 0x77, 0x73, 0x2e, 0x41, 0x72, 0x72, 0x61, 0x79, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x4e, 0x65, 0x77, 0x73, 0x22, 0x00, 0x30, 0x01, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x2e, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_apigetway_proto_rawDescOnce sync.Once
	file_apigetway_proto_rawDescData = file_apigetway_proto_rawDesc
)

func file_apigetway_proto_rawDescGZIP() []byte {
	file_apigetway_proto_rawDescOnce.Do(func() {
		file_apigetway_proto_rawDescData = protoimpl.X.CompressGZIP(file_apigetway_proto_rawDescData)
	})
	return file_apigetway_proto_rawDescData
}

var file_apigetway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_apigetway_proto_goTypes = []interface{}{
	(*ShortNew)(nil),       // 0: rpc_news.ShortNew
	(*Forlist)(nil),        // 1: rpc_news.Forlist
	(*Page)(nil),           // 2: rpc_news.Page
	(*Id)(nil),             // 3: rpc_news.Id
	(*ArrayShortNews)(nil), // 4: rpc_news.ArrayShortNews
	(*Result)(nil),         // 5: rpc_news.Result
}
var file_apigetway_proto_depIdxs = []int32{
	0, // 0: rpc_news.ArrayShortNews.Sl:type_name -> rpc_news.ShortNew
	0, // 1: rpc_news.NewsService.AddNew:input_type -> rpc_news.ShortNew
	4, // 2: rpc_news.NewsService.AddNews:input_type -> rpc_news.ArrayShortNews
	1, // 3: rpc_news.NewsService.List:input_type -> rpc_news.Forlist
	2, // 4: rpc_news.NewsService.ListPage:input_type -> rpc_news.Page
	5, // 5: rpc_news.NewsService.AddNew:output_type -> rpc_news.Result
	5, // 6: rpc_news.NewsService.AddNews:output_type -> rpc_news.Result
	4, // 7: rpc_news.NewsService.List:output_type -> rpc_news.ArrayShortNews
	4, // 8: rpc_news.NewsService.ListPage:output_type -> rpc_news.ArrayShortNews
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apigetway_proto_init() }
func file_apigetway_proto_init() {
	if File_apigetway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_apigetway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShortNew); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigetway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Forlist); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigetway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Page); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigetway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigetway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayShortNews); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_apigetway_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_apigetway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apigetway_proto_goTypes,
		DependencyIndexes: file_apigetway_proto_depIdxs,
		MessageInfos:      file_apigetway_proto_msgTypes,
	}.Build()
	File_apigetway_proto = out.File
	file_apigetway_proto_rawDesc = nil
	file_apigetway_proto_goTypes = nil
	file_apigetway_proto_depIdxs = nil
}
